Update AboutUs
BAID-CSClub/baid-website-next pull request #119
Opened 2023-08-02 06:46 UTC by Henry3510

2023-08-03 00:44 UTC, lihe07 requested changes

2023-08-03 00:44 UTC, lihe07 commented on src/components/DesktopAboutUs/AlumniSection.vue
>  import NotFancyTitle from '../NotFancyTitle.vue'
Delete
```js
import imgAlum1 from '../../assets/images/AboutUs/Alumni/Alum_1.jpeg?webp'
import imgAlum2 from '../../assets/images/AboutUs/Alumni/Alum_2.jpeg?webp'
import imgAlum3 from '../../assets/images/AboutUs/Alumni/Alum_3.jpeg?webp'
```
to pass the check.

2023-08-05 10:24 UTC, Henry3510 commented
还是不对 @lihe07

2023-08-06 11:59 UTC, lihe07 approved these changes

2023-08-06 11:59 UTC, merged