CampusLife Draft
BAID-CSClub/baid-website-next pull request #28
Opened 2022-08-06 14:55 UTC by Thunderw1nd

我的评价是之后慢慢填坑

2022-08-06 15:06 UTC, Henry3510 requested changes

2022-08-06 15:06 UTC, Henry3510 commented on src/views/desktop/CampusLife.vue
> +import campusBg1 from '../../assets/images/campusBg1.png?webp'
Where is this pic?

2022-08-06 15:07 UTC, Henry3510 commented on src/views/desktop/CampusLife.vue
> +import campusBg1 from '../../assets/images/campusBg1.png?webp'
campusBg1

2022-08-07 01:11 UTC, lihe07 requested changes
总体上没问题
以下部分需要修改：
- 移除多余的 `id`
- 在 `assets` 中补充占坑图片

2022-08-07 01:11 UTC, lihe07 commented on src/views/desktop/CampusLife.vue
> +import campusBg1 from '../../assets/images/campusBg1.png?webp'
@Thunderw1nd  如果引入了新的占坑图片，请创建对应的文件，不然编译不能通过

2022-08-07 01:11 UTC, lihe07 commented on src/components/DesktopCampusLife/ActivitiesSection.vue
> +            <div id="selected" class="p-0">
如果没有实际作用，尽量不用为element添加 `id` 属性
所有的 `section` 建议附加 id，方便定位（但是不是必须的）

其他的 `id` 可以被删除，以防止重复

2022-08-07 02:06 UTC, Henry3510 approved these changes

2022-08-07 02:08 UTC, lihe07 approved these changes

2022-08-07 02:08 UTC, merged